name                  = "cardex-api"
main                  = "src/index.ts"
compatibility_date    = "2024-01-01"
compatibility_flags   = ["nodejs_compat"]

[[kv_namespaces]]
binding = "CARDEX_KV"
id      = "c10dfc1b686d4d95a207bc18f5f96573"

[vars]
FRONTEND_ORIGIN  = "https://cardex.tjm.sk"
FRONTEND_RP_ID   = "cardex.tjm.sk"
EMAIL_FROM       = "cardex@tjm.sk"
EMAIL_FROM_NAME  = "Cardex Team"

# Secrets — set via CLI, never commit values:
#   wrangler secret put JWT_SECRET
#   wrangler secret put BREVO_API_KEY

[dev]
port = 8787
